# Rime default settings for T9Bopomofo (librime)
# encoding: utf-8

config_version: "0.2"

schema_list:
  - schema: bopomofo_phone
  - schema: bopomofo_t9

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  page_size: 9

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  import_preset: default

recognizer:
  import_preset: default

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
